# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on: [push, pull_request]

jobs:
  compilation_check_for_test_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd test-site && pwd && ls
