# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on: [push, pull_request]

jobs:
  call_run_tests:
    uses: yext/slapshot-reusable-workflows/.github/workflows/run_tests.yml@v1
    with:
      build_script: npm run build-ci

  test_site_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build
      - run: cd test-site
      - run: npm i
      - run: npm run build
